Repository ais-internship-cnu/I-school-FE, pull requests merged in 2024-07, with the labels that each got.

#8 refactor: "코드 리팩토링"
  README.md
  src/app/practice-page/page.tsx
  src/app/review-page/page.tsx
  src/components/page/Practice/Agreement/index.tsx
  src/components/page/Practice/index.tsx
  src/components/page/Review/ReviewCard/index.tsx
  src/components/page/Review/index.tsx
  src/constant/api/index.ts
  src/hooks/index.ts
  src/hooks/usePractice.ts
  src/hooks/useReview.ts
  src/mocks/employeeMock/index.ts
  src/mocks/reviewMock/index.ts
  src/redux/modules/index.ts
  src/redux/modules/practice/index.ts
  src/redux/modules/review/index.ts
  src/styles/common.css
  src/types/practice.ts
  src/types/review.ts
  src/utill/axios.ts
Labels: ✨ Feature

#10 feat: 일부 홈화면 ui 작성
  package-lock.json
  package.json
  public/img/book-club.png
  public/img/chat.png
  public/img/stack-of-books.png
  src/app/example-page/page.tsx
  src/app/globals.css
  src/app/home-page/page.tsx
  src/app/layout.tsx
  src/components/page/Home/free-board-button.tsx
  src/components/page/Home/title.tsx
  src/styles/homeStyle.css
Labels: ✨ Feature

#11 feat: 강의평 등록개발_Header,star_rating,courese_review,reg_button
  next.config.mjs
  src/app/example-page/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/review-register-page/page.tsx
  src/components/page/Example/index.tsx
  src/components/page/ReviewRegister/course_review.tsx
  src/components/page/ReviewRegister/header.tsx
  src/components/page/ReviewRegister/register_button.tsx
  src/components/page/ReviewRegister/star_rating.tsx
  src/styles/common.css
  src/styles/review-register.css
Labels: ✨ Feature

#12 fix: container div 제거 및 홈 화면 button 레이아웃 수정
  src/app/example-page/page.tsx
  src/app/layout.tsx
  src/components/page/Home/free-board-button.tsx
  src/styles/homeStyle.css
Labels: 🐞 BugFix

#13 feat: 강의평 목록을 렌더링 하는 기능 추가
  src/app/example-page/page.tsx
  src/components/page/Review/ReviewCard/index.tsx
  src/components/page/Review/index.tsx
  src/mocks/reviewMock/index.ts
  src/types/review.ts
Labels: ✨ Feature

#17 feat: 시간표 Mock 데이터 불러오는 기능
  src/app/review-page/page.tsx
  src/app/timetable-page/page.tsx
  src/components/page/Timetable/TimetableCard/index.tsx
  src/components/page/Timetable/index.tsx
  src/constant/api/index.ts
  src/hooks/useTimetable.ts
  src/mocks/timetableMock/index.ts
  src/redux/modules/index.ts
  src/redux/modules/timetable/index.ts
  src/types/timetable.ts
  src/utill/axios.ts
Labels: ✨ Feature

#19 feat: review page UI 구현
  public/img/empty-star.png
  public/img/full-star.png
  public/img/half-star.png
  src/app/review-page/page.tsx
  src/components/page/Review/ReviewCard/index.tsx
  src/components/page/Review/header.tsx
  src/components/page/Review/index.tsx
  src/components/page/Review/navigation.tsx
  src/styles/review.css
Labels: ✨ Feature

#20 feat: 네비게이션 클릭 효과 추가
  src/app/home-page/page.tsx
  src/components/page/Home/navigator.tsx
  src/styles/homeStyle.css
Labels: ✨ Feature

#21 feat: page 레이아웃, 검색창, 검색버튼, 검색결과 block 및 slider, button에 url 부여.
  src/app/course-page/page.tsx
  src/components/page/CourseSearcher/index.tsx
  src/components/page/Courses/CourseBlock/index.tsx
  src/components/page/Courses/index.tsx
  src/mocks/reviewMock/mockData.ts
  src/styles/course-search-style.css
  src/types/courses.ts
Labels: ✨ Feature

#22 feat: 시간표 데이터 렌더링 기능 추가
  src/components/page/Timetable/TimetableCard/index.tsx
  src/components/page/Timetable/index.tsx
  src/mocks/timetableMock/index.ts
  src/styles/common.css
  src/types/timetable.ts
Labels: ✨ Feature

#24 feat: post 요청 보내는 로직 구현
  .env.development
  .env.production
  src/app/review-register-page/page.tsx
  src/components/page/ReviewRegister/course_review.tsx
  src/components/page/ReviewRegister/header.tsx
  src/components/page/ReviewRegister/register.tsx
  src/components/page/ReviewRegister/register_button.tsx
  src/components/page/ReviewRegister/star_rating.tsx
  src/constant/api/index.ts
  src/hooks/useReview.ts
  src/redux/modules/review/index.ts
  src/types/reviewRegister.ts
  src/utill/axios.ts
Labels: ✨ Feature

#36 feat: 시간표 강의 클릭 시 모달창 출력
  src/components/page/TimeTable/Header.tsx
  src/components/page/TimeTable/TimetableModal.tsx
  src/components/page/Timetable/index.tsx
  src/styles/timetable.css
Labels: ✨ Feature

#37 fix: build시 발생되는 오류 해결
  .eslintignore
  src/components/page/Home/navigator.tsx
Labels: 🐞 BugFix

#40 feat: 과목코드와 교수명으로 강의평 데이터를 받아오는 기능 구현
  src/app/review-page/[course_name]/[professor]/page.tsx
  src/app/review-page/page.tsx
  src/components/common/Star/index.tsx
  src/components/page/Review/AverageStar.tsx
  src/components/page/Review/ReviewCard/index.tsx
  src/components/page/Review/header.tsx
  src/components/page/Review/index.tsx
  src/components/page/Review/navigation.tsx
  src/components/page/TimeTable/Header.tsx
  src/components/page/TimeTable/TimetableModal.tsx
  src/components/page/Timetable/index.tsx
  src/hooks/useReview.ts
  src/redux/modules/review/index.ts
Labels: ✨ Feature

#41 feat: 시간표 추가기능 사용시 출력되는 간이페이지 레이아웃 구현
  src/app/bottom-sheet-sample/page.tsx
  src/components/page/TimeTable/BottomSheet/BottomSheetCourseBlock/index.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/styles/bottom-sheet-style.css
Labels: ✨ Feature

#43 feat: 강의평을 누르면 해당 강의평 페이지로 이동기능 구현
  src/components/page/TimeTable/TimetableModal.tsx
  src/components/page/Timetable/TimetableCard/index.tsx
  src/components/page/Timetable/index.tsx
  src/mocks/timetableMock/index.ts
  src/types/timetable.ts
Labels: ✨ Feature

#44 fix: 홈화면 기능 이름 및 내비게이션 바 오류 수정, 강의평 버튼 기능 추가
  src/app/home-page/page.tsx
  src/components/page/Home/home-button.tsx
  src/components/page/Home/navigator.tsx
Labels: 🐞 BugFix, ✨ Feature

#46 feat: post요청 로직 디테일 구성
  package-lock.json
  package.json
  src/components/page/ReviewRegister/register.tsx
  src/hooks/useReview.ts
  src/redux/modules/review/index.ts
  src/types/reviewRegister.ts
  src/utill/axios.ts
Labels: ✨ Feature

#47 fix: 강의평 버튼 클릭 기능 수정
  src/components/page/Home/home-button.tsx
  src/utill/axios.ts
Labels: 🐞 BugFix

#48 feat: 강의실 블록 클릭에 대응해 해당 강의의 강의평으로 이동.
  src/app/bottom-sheet-sample/page.tsx
  src/components/page/Courses/CourseBlock/index.tsx
Labels: ✨ Feature

#53 fix: 전체 화면에 스크롤이 나타나는 현상 수정
  src/components/page/Home/navigator.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/styles/bottom-sheet-style.css
Labels: 🐞 BugFix

#54 feat: 강의평 버튼 클릭 시 courseid 인자 넘겨주기
  src/app/review-page/[course_name]/[professor]/page.tsx
  src/components/page/Review/header.tsx
Labels: ✨ Feature

#55 feat: 타임테이블 바텀시트 필터핑 기능
  src/components/page/TimeTable/BottomSheet/BottomSheetCourseBlock/index.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/components/page/TimeTable/GradeSelect.tsx
  src/components/page/TimeTable/MajorSelect.tsx
  src/styles/bottom-sheet-style.css
Labels: ✨ Feature

#56 feat: 강의평 등록 페이지에 course_id 인자를 넘기는 기능 구현
  src/app/review-page/[course_name]/[professor]/[course_id]/page.tsx
  src/components/page/TimeTable/TimetableModal.tsx
  src/components/page/Timetable/TimetableCard/index.tsx
Labels: ✨ Feature

#65 fix: bottomsheet 강의로딩 무한루프 해결
  src/app/bottom-sheet-sample/page.tsx
  src/app/course-page/page.tsx
  src/components/page/Courses/index.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/hooks/useBottomSheetCourse.ts
  src/mocks/reviewMock/mockData.ts
  src/redux/modules/index.ts
  src/redux/modules/timetable/bottomSheet/index.ts
  src/types/bottomSheetCourses.ts
  src/types/timetable.ts
Labels: 🐞 BugFix

#69 fix: 강의실/ 강의평 데이터불러오기 꼬임 해결
  src/components/page/TimeTable/BottomSheet/BottomSheetCourseBlock/index.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/constant/api/index.ts
  src/types/bottomSheetCourses.ts
Labels: 🐞 BugFix

#70 feat: 카멜케이스 -> 스네이크 케이스 변경 로직 적용
  .env.development
  .env.production
  src/constant/api/index.ts
  src/redux/modules/courses/index.ts
  src/redux/modules/review/index.ts
  src/redux/modules/timetable/bottomSheet/index.ts
  src/redux/modules/timetable/index.ts
  src/utill/convertType.ts
Labels: ✨ Feature

#71 fix: 백엔드 응답과 타입이 맞지 않은 오류 해결
  src/components/page/Timetable/TimetableCard/index.tsx
  src/mocks/timetableMock/index.ts
  src/redux/modules/timetable/index.ts
  src/types/timetable.ts
Labels: ✨ Feature

#72 fix: timetable 관련 로직 원상복구
  src/components/page/Timetable/TimetableCard/index.tsx
  src/mocks/timetableMock/index.ts
  src/redux/modules/timetable/index.ts
  src/types/timetable.ts
Labels: 🐞 BugFix

#73 fix: 시간표 렌더링 하는 기능 구현
  src/redux/modules/timetable/index.ts
Labels: 🐞 BugFix

#75 fix: api 정보받기,
  src/app/course-page/page.tsx
  src/app/timetable-page/page.tsx
  src/components/page/Courses/BackButton/index.tsx
  src/components/page/Courses/CourseBlock/index.tsx
  src/components/page/Courses/index.tsx
  src/constant/api/index.ts
  src/redux/modules/courses/index.ts
  src/styles/course-search-style.css
  src/types/courses.ts
Labels: 📬 API

#76 feat: 강의평 불러오는 API 로직 구현
  src/app/timetable-page/page.tsx
  src/components/page/Review/ReviewCard/index.tsx
  src/components/page/Review/index.tsx
  src/components/page/TimeTable/TimetableModal.tsx
  src/hooks/useReview.ts
  src/mocks/reviewMock/index.ts
  src/redux/modules/review/index.ts
  src/types/review.ts
Labels: 📬 API

#78 fix: bottom page에서 강의평이 특정한 강의로만 들어가지는 현상 해결
  src/components/page/TimeTable/BottomSheet/BottomSheetCourseBlock/index.tsx
Labels: 🐞 BugFix

#79 fix: bottom sheet에 강의가 두 개씩 나오는 현상 해결
  src/components/page/TimeTable/BottomSheet/BottomSheetCourseBlock/index.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
Labels: 🐞 BugFix

#80 fix: 강의평 검색화면 뒤로가기버튼 삽입 및 시간표 텍스트 검색 정상화
  src/app/timetable-page/page.tsx
  src/components/page/TimeTable/BottomSheet/index.tsx
  src/styles/course-search-style.css
Labels: 🐞 BugFix
